### ISSUE TITLE
auto spoof on new connection

### ISSUE THREAD

**Issue by srulikuk** [jerabaul29/randommac#2]
Hi,
before ubuntu 16.04 macchnager (or any other method to change MAC) worked fine, and as you mention in the description since 16.04 this is not the case, i use to just set the mac before connection to a network, this is no more the case as nmcli (or nm-applet) resets the MAC when connecting to a network.

I am looking for some way to hook the script to nm-applet to set a random mac when connecting to any network, new or existing, i need it to execute when connecting using nm-applet (gui).

Is there a way to do it with your script?

Thanks

**Comment by jerabaul29** [comment]
Hej!

Sorry for the late answer, I have been quite busy lately.

First I should give credits to T.K. for suggesting a (possible) solution to your problem.

As I understand it, this is not really a question of whether my scripts are able to perform the spoofing you want given the right parameters (this should be OK), but rather of finding a way to automatically launch the script with the right parameters when using the nm-applet gui interface to connect to a new network.

You should be able to do this kind of hooking using the `NetworkManager-dispatcher.service`, see more details here:

https://wiki.archlinux.org/index.php/NetworkManager#Network_services_with_NetworkManager_dispatcher

So at this point I should say I did not test any of this, but you should be able to get the interface ($1) and the status ($2) as well as the network UUID for giving them as arguments to the scripts if needed. See for example some discussions:

https://blog.rabin.io/linux/networkmanager-using-dispatcher-d-to-run-scripts-based-on-network-connectivity

http://sysadminsjourney.com/content/2008/12/18/use-networkmanager-launch-scripts-based-network-location/

I do not know if there is a risk of the true MAC leaking in the process (I guess there is if one is not careful in the design of the scripts)...

- Does this answer your question?
- Are you able to get it to work?

If you get some nicely working pieces of script and want to share them, could you put a link to the place where you make them accessible in this discussion thread (or add a folder and push it to this repo)?

**Comment by srulikuk** [comment]
Thanks for your response, I found that versions of NM after 1.4.4 work fine and its simple to set the MAC parameters in the global or per connection config, I suspect that to achieve what I wanted with ubuntu NM version 1.2.2 (on 16.04) it would be way too much work to achieve, so just updated the NM package fromhttps://launchpad.net/~lkundrak/+archive/ubuntu/network-manager-daily-stable
